### ISSUE TITLE
ACaPS Latency

### ISSUE THREAD

**Issue by pkarnia** [iit-ideashop/check-in-app#13]
Measured 22.58 second latency for registration of new users. Almost certainly due to lag with ACaPS, confirm at Tower basement. If lag persists in multiple locations then contact ACaPS. Other alternative is to tried wired connection to check latency.

**Comment by pkarnia** [comment]
Other alternatives are to show a retrieving student data screen or share hawkcard and user databases between locations since it is all the same department.

**Comment by nkaminski** [comment]
I like the shared cache for card -> user mappings approach; you wouldn't even need guaranteed persistence so you could use something less durable than mariadb but very fast at scale (like redis) for this.

Redis get/set operations are O(1) complexity   and typically complete in microseconds.

Nash

On October 19, 2018 8:39:08 AM CDT, Patrick Karnia <notifications@github.com> wrote:
>Other alternatives are to show a retrieving student data screen or
>share hawkcard and user databases between locations since it is all the
>same department.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/iit-ideashop/check-in-app/issues/13#issuecomment-431366339

-- 
Sent from my Android device with K-9 Mail.

**Comment by tman0** [comment]
The shared cache is a good idea but I don't think setting up Redis for this would be worth it given the incredibly small number of concurrent users. We can just create a duplicate record from existing data in the user table.

Other option is to contact ACaPS and figure out the root cause of the issue. I haven't had time to test this yet between my IPRO, Pumpkin Launch, and general homework but I should have time to get on this next week.

**Comment by nkaminski** [comment]
Fair enough, Patrick mentioned several more deployments and I wasn't sure what "several" in this context exactly meant. This is likely an over-engineered solution until you get beyond a couple requests per second.

Of course addressing the root cause of the latency is the best solution, provided that ACaPS is responsive and willing.

On October 19, 2018 11:39:12 AM CDT, tman0 <notifications@github.com> wrote:
>The shared cache is a good idea but I don't think setting up Redis for
>this would be worth it given the incredibly small number of concurrent
>users. We can just create a duplicate record from existing data in the
>user table.
>
>Other option is to contact ACaPS and figure out the root cause of the
>issue. I haven't had time to test this yet between my IPRO, Pumpkin
>Launch, and general homework but I should have time to get on this next
>week.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/iit-ideashop/check-in-app/issues/13#issuecomment-431424030

-- 
Sent from my Android device with K-9 Mail.

**Comment by tman0** [comment]
A couple of other labs on campus have expressed interest in using the system, but at least as far as ACaPS requests go we're talking like 5-6 requests/minute absolute worst case scenario.

**Comment by pkarnia** [comment]
After further investigation w/ @nkaminski internal DNS breakage (per new OTS configurations) was the result of latency out to ACaPS servers. Application latency is back to sub second. Follow-up with OTS to conveigh DNS, routing and NIC configuration changes should be done early next week to avoid further breakage.
