### ISSUE TITLE
Database Reorganization

### ISSUE THREAD

**Issue by tellowkrinkle** [iit-ideashop/check-in-app#21]
At the moment, these tables in the database contain a column for `location_id`:
- access
- adminLog
- hawkcards (primary key)
- kiosks (primary key)
- locations (primary key)
- machines
- scanLog
- types
- users (primary key)

Of these, the only ones that actually need it are access, adminLog, kiosks, locations, machines, and scanLog and only locations needs it as a primary key.  In tables like users and hawkcards, the requirement makes the database have to have three rows for the same user, each with their own PIN (and I don't think people actually want to have their PIN be different depending on which kiosk they're logging in at) and ends up requiring unnecessary code like this
https://github.com/iit-ideashop/check-in-app/blob/ad934cfde8328c88c1c96e1c8a031a36a754154f/checkIn/checkIn.py#L984-L990
https://github.com/iit-ideashop/check-in-app/blob/ad934cfde8328c88c1c96e1c8a031a36a754154f/checkIn/checkIn.py#L1125-L1136

If we want to support having separate types and waiverSigned entries per pair of user and location (we probably do since that's how we manage bans) we should make a separate table for that instead of requiring duplicates of all the other data along with.

Based on this I would like to reorganize the database and remove the location_id requirement on tables that don't need it

Since doing this will require a manual database migration, I would like to take the time to fix a few other issues with the database schema:
- `sid`s are stored as a bigint even though SIDs are only 8 digits.
- hawkcards has a facility field that is null in 100% of entries
- kiosks.last_seen is nullable even though there's no reason we'd have a kiosk in the database without knowing when we last saw it
- machines.name is nullable (do we really want to allow having machines without names?)
- in safetyTraining, trainee_id, trainer_id, machine_id, and date are all nullable.  None of these seem like things that should be allowed to be null
- scanLog.time is nullable (how can we know that someone scanned a card without knowing when)
- scanLog has a facility_id that is null in 100% of entries

**Comment by tman0** [comment]
I think that's a good solution... the only reason I had users separated by location to begin with was that Patrick had mentioned that other spaces on campus and potentially other schools are interested in using this system, and I wanted to have a separate user entry to maintain separate types and waiver signature dates as well as to prevent collisions in those cases. A lot of this is a relic from band-aiding on multiple location support to our existing database.
* Changing `sid`s to an 8 digit number with validity checks is probably a good idea, but again other schools have expressed interest in this system and they likely will not follow our standards.
* Multiple facility code support should be added to the to-do list
* Everything you mentioned that's nullable is probably that way due to an oversight when I was designing the database... we should make everything you mentioned non-nullable.
* `scanLog` itself is also kind of redundant but is also there on Patrick's request.

**Comment by tellowkrinkle** [comment]
>     Changing `sid`s to an 8 digit number with validity checks is probably a good idea, but again other schools have expressed interest in this system and they likely will not follow our standards.

Since there's no guarantee other schools' IDs are even numbers (and they definitely won't be getting their SIDs from ACaPS) why don't we make a variable called `StudentIDType` or something and set it to `sa.Integer` so that it's easy to change if someone wants to change it
